### PR TITLE
Initial Version of Ember.js Client App

### PR DESCRIPTION
**Pull request by aboma**
Initial version of Tribute-Web client with Projects, Teams, Companies and ProjectUser relationships.  To-do: create project-team relationship; create team forms.

### CODE REVIEW

**Comment by dblock** [comment]
Awesome. I'll take a look very soon!

**Comment by dblock** [comment]
Merged. The next thing to do is to get tests to work, and actually test something useful, before we add a ton of functionality. And let me know what API you want first.

**Comment by aboma** [comment]
Take a look at the fixtures file for the API details.  I will add tests
soon.

For the form where users give tribute, I assume that the project, company
and or team may or may not exist.  This adds some complexity but I have
some ideas.  Are users going to be able to edit entries for any
company/team or are they going to be restricted to one? What other
restrictions do you have in mind?

**Comment by aboma** [comment]
hi Daniel,

I haven't been able to get back to this project but I hope to do by
December at the latest. I have been getting my own open-source project off
the ground and starting a job search. My apologies.

Adrian

**Pull request merged**
